### PR TITLE
ci: init

### PR DESCRIPTION
**Pull request by mrtnvgr**
Add Github Workflow job for CI testing

### CODE REVIEW

**Comment by Mnwa** [comment]
Hi! Can you add clippy checks?

**Comment by mrtnvgr** [comment]
I've included some custom lints if you don't mind. Can I fix clippy errors here or should I create a new PR?

**Comment by Mnwa** [comment]
Thanks! To can add fixes here

**Comment by mrtnvgr** [comment]
I skipped the [`module_name_repetitions`](https://rust-lang.github.io/rust-clippy/master/index.html#/module_name_repetitions) lint. It requires to change the naming of public objects.

**Comment by Mnwa** [comment]
Thanks!

**Pull request merged**
